name: gmatic
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- astalavista=4.0=0
- bcftools=1.5=3
- bedtools=2.25.0=2
- biopython=1.70=np112py36_1
- bismark=0.19.0=pl5.22.0_0
- blast=2.7.1=boost1.64_1
- bleach=1.4.2=py36_0
- bowtie=1.2.2=py36pl5.22.0_0
- bowtie2=2.3.2=py36pl5.22.0_1
- bwa=0.7.17=pl5.22.0_1
- clustalw=2.1=1
- cufflinks=2.2.1=py36_1
- cutadapt=1.16=py36_1
- deeptools=2.5.3=py36_0
- dropbox=5.2.1=py36_0
- fastqc=0.11.5=pl5.22.0_2
- fastx_toolkit=0.0.14=pl5.22.0_6
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- gfold=1.1.4=gsl1.16_1
- hisat2=2.1.0=py36pl5.22.0_0
- hmmer=3.1b2=3
- homer=4.9.1=pl5.22.0_5
- htslib=1.5=0
- igvtools=2.3.93=0
- jellyfish=1.1.11=1
- kraken=1.0=pl5.22.0_0
- libgtextutils=0.7=3
- manormfast=0.1.2=py36_1
- megahit=1.1.2=py36_0
- mysql-connector-c=6.1.6=2
- parallel=20170422=pl5.22.0_0
- perl-gd=2.56=pl5.22.0_6
- perl-gdgraph=1.49=pl5.22.0_3
- perl-gdgraph-histogram=1.1=pl5.22.0_1
- perl-gdtextutil=0.86=pl5.22.0_3
- perl-perlio-gzip=0.19=pl5.22.0_1
- perl-threaded=5.22.0=pl5.22.0_12
- picard=2.15.0=py36_0
- py2bit=0.2.1=py36_0
- pybedtools=0.7.10=py36_1
- pybigwig=0.3.4=np112py36_0
- pysam=0.11.2.2=py36_1
- pysftp=0.2.9=py36_0
- qualimap=2.2.2a=1
- samtools=1.5=0
- seqkit=0.7.2=0
- seqtk=1.2=0
- snakemake=3.13.3=py36_0
- sra-tools=2.8.2=0
- star=2.5.3a=0
- trimmomatic=0.36=4
- ucsc-bigwigtobedgraph=357=0
- ucsc-wigtobigwig=357=0
- vcftools=0.1.15=0
- xopen=0.3.2=py36_0
- asn1crypto=0.22.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- boost=1.64.0=py36_4
- boost-cpp=1.64.0=1
- bzip2=1.0.6=1
- ca-certificates=2018.4.16=0
- cairo=1.14.6=4
- certifi=2017.4.17=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.2=py36_1
- cryptography=1.9=py36_0
- curl=7.54.1=0
- cycler=0.10.0=py36_0
- cython=0.28.2=py36_0
- dbus=1.10.10=3
- decorator=4.1.2=py36_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.1=0
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- gnuplot=5.2.0=0
- gnutls=3.5.15=0
- graphite2=1.3.9=0
- gsl=1.16=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- harfbuzz=1.4.3=0
- html5lib=1.0.1=py_0
- icu=58.1=1
- idna=2.5=py36_0
- ipykernel=4.8.2=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_1
- jupyter_client=5.2.3=py36_0
- jupyter_core=4.4.0=py_0
- krb5=1.14.2=0
- libffi=3.2.1=3
- libgd=2.2.5=0
- libiconv=1.14=4
- libidn11=1.33=0
- libpng=1.6.28=1
- libsodium=1.0.16=0
- libssh2=1.8.0=1
- libtiff=4.0.6=7
- libuuid=1.0.3=1
- libwebp=0.5.2=7
- libxcb=1.12=1
- libxml2=2.9.4=4
- markupsafe=1.0=py36_0
- matplotlib=2.1.0=py36_1
- mistune=0.8.3=py_0
- mmtf-python=1.0.9=py_0
- msgpack-python=0.4.8=py36_0
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- nettle=3.3=0
- nose=1.3.7=py36_2
- notebook=5.4.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- pandocfilters=1.4.1=py36_0
- pango=1.40.4=0
- paramiko=2.2.1=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=0
- perl=5.22.0.1=0
- pexpect=4.3.0=py36_0
- pickleshare=0.7.4=py36_0
- pigz=2.3.4=0
- pillow=4.3.0=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py36_0
- psutil=5.2.1=py36_0
- ptyprocess=0.5.2=py36_0
- pyasn1=0.2.3=py36_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pynacl=1.1.2=py36_0
- pyopenssl=16.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.7=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_1
- pyzmq=17.0.0=py36_4
- qt=5.6.2=3
- readline=6.2=0
- reportlab=3.4.0=py36_0
- requests=2.18.1=py36_0
- send2trash=1.5.0=py_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- sqlite=3.13.0=0
- tbb=2018_20171205=0
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.21.1=py36_1
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- wrapt=1.10.8=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- yaml=0.1.6=0
- zeromq=4.2.5=1
- zlib=1.2.8=3
- bcrypt=3.1.3=py36_0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- nbconvert=5.2.1=py36_0
- numpy=1.12.1=py36_0
- openjdk=8.0.121=1
- scipy=0.19.1=np112py36_0
- setuptools=27.2.0=py36_0
- statsmodels=0.8.0=np112py36_0
- tk=8.5.18=0
- xz=5.2.2=1
- pip:
  - aenum==2.0.9
  - avro-cwl==1.8.4
  - backports.functools-lru-cache==1.4
  - beautifulsoup4==4.6.0
  - bioblend==0.10.0
  - boto==2.48.0
  - cachecontrol==0.11.7
  - click==6.7
  - configparser==3.5.0
  - cwltool==1.0.20170828135420
  - ephemeris==0.8.0
  - future==0.16.0
  - galaxy-lib==17.9.10
  - glob2==0.6
  - gxformat2==0.1.1
  - htseq==0.9.1
  - ipython-genutils==0.2.0
  - isodate==0.6.0
  - jupyter-client==5.2.3
  - jupyter-core==4.4.0
  - lockfile==0.12.2
  - lxml==4.1.1
  - prompt-toolkit==1.0.15
  - pyaml==17.12.1
  - rdflib==4.2.2
  - rdflib-jsonld==0.4.0
  - requests-toolbelt==0.8.0
  - ruamel.yaml==0.14.12
  - schema-salad==2.6.20171201034858
  - shellescape==3.4.1
  - typing==3.6.2
  - virtualenv==15.1.0
prefix: /home/xfu/miniconda2/envs/gmatic

