name: gmatic
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bcftools=1.5=3
- bedtools=2.26.0=0
- bioconductor-annotate=1.50.0=r3.3.2_1
- bioconductor-annotationdbi=1.38.0=r3.3.2_0
- bioconductor-annotationforge=1.14.2=r3.3.2_0
- bioconductor-biobase=2.34.0=r3.3.2_0
- bioconductor-biocgenerics=0.20.0=r3.3.2_0
- bioconductor-biocparallel=1.6.6=r3.3.2_1
- bioconductor-biomart=2.28.0=r3.3.2_0
- bioconductor-biostrings=2.42.1=r3.3.2_0
- bioconductor-bsgenome=1.42.0=r3.3.2_0
- bioconductor-category=2.38.0=r3.3.2_1
- bioconductor-chipseeker=1.10.0=r3.3.2_0
- bioconductor-deseq2=1.14.1=r3.3.2_0
- bioconductor-diffbind=1.16.3=0
- bioconductor-dnacopy=1.48.0=r3.3.2_0
- bioconductor-do.db=2.9=r3.3.2_0
- bioconductor-dose=2.10.7=r3.3.2_0
- bioconductor-edger=3.16.5=r3.3.2_0
- bioconductor-genefilter=1.58.1=r3.3.2_0
- bioconductor-geneplotter=1.50.0=r3.3.2_0
- bioconductor-genomeinfodb=1.10.3=r3.3.2_0
- bioconductor-genomicalignments=1.10.0=r3.3.2_0
- bioconductor-genomicfeatures=1.26.4=r3.3.2_0
- bioconductor-genomicranges=1.26.4=r3.3.2_0
- bioconductor-go.db=3.4.0=r3.3.2_0
- bioconductor-gosemsim=1.30.3=r3.3.2_0
- bioconductor-gostats=2.38.1=r3.3.2_1
- bioconductor-graph=1.50.0=r3.3.2_1
- bioconductor-gseabase=1.34.1=r3.3.2_0
- bioconductor-iranges=2.8.2=r3.3.2_0
- bioconductor-limma=3.30.13=r3.3.2_0
- bioconductor-medips=1.24.0=r3.3.2_0
- bioconductor-preprocesscore=1.34.0=r3.3.2_0
- bioconductor-qvalue=2.6.0=r3.3.2_0
- bioconductor-rbgl=1.48.1=r3.3.2_1
- bioconductor-rsamtools=1.26.1=r3.3.2_0
- bioconductor-rtracklayer=1.34.2=r3.3.2_1
- bioconductor-s4vectors=0.12.2=r3.3.2_0
- bioconductor-shortread=1.32.0=r3.3.2_0
- bioconductor-summarizedexperiment=1.4.0=r3.3.2_2
- bioconductor-sva=3.20.0=r3.3.2_0
- bioconductor-systempiper=1.9.0=r3.3.2_0
- bioconductor-topgo=2.24.0=r3.3.2_1
- bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2=r3.3.2_0
- bioconductor-tximport=1.0.3=r3.3.2_1
- bioconductor-variantannotation=1.20.3=r3.3.2_0
- bioconductor-xvector=0.14.1=r3.3.2_0
- bioconductor-zlibbioc=1.20.0=r3.3.2_1
- bowtie2=2.3.2=py36pl5.22.0_1
- cufflinks=2.2.1=py36_1
- deeptools=2.5.3=py36_0
- dropbox=5.2.1=py36_0
- fastqc=0.11.5=pl5.22.0_2
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- gfold=1.1.4=gsl1.16_1
- hisat2=2.1.0=py36pl5.22.0_0
- htslib=1.5=0
- igvtools=2.3.93=0
- manormfast=0.1.2=py36_1
- py2bit=0.2.1=py36_0
- pybedtools=0.7.10=py36_1
- pybigwig=0.3.4=np112py36_0
- pysam=0.11.2.2=py36_1
- pysftp=0.2.9=py36_0
- qualimap=2.2.2a=1
- r-amap=0.8_14=r3.3.2_1
- r-batchjobs=1.6=r3.3.2_0
- r-bbmisc=1.11=r3.3.2_0
- r-bh=1.60.0_2=r3.3.2_0
- r-catools=1.17.1=r3.3.2_1
- r-checkmate=1.8.2=r3.3.2_0
- r-data.table=1.10.4=r3.3.2_0
- r-digest=0.6.12=r3.3.2_0
- r-dplyr=0.5.0=r3.3.2_1
- r-fail=1.3=r3.3.2_0
- r-futile.logger=1.4.1=r3.3.2_0
- r-futile.options=1.0.0=r3.3.2_0
- r-getopt=1.20.0=r3.3.2_0
- r-ggplot2=2.2.1=r3.3.2_0
- r-gplots=2.17.0=r3.3.2_0
- r-htmltools=0.3=r3.3.2_0
- r-htmlwidgets=0.5=r3.3.2_0
- r-hwriter=1.3.2=r3.3.2_0
- r-jsonlite=0.9.19=r3.3.2_1
- r-knitr=1.12.3=r3.3.2_0
- r-lambda.r=1.1.7=r3.3.2_0
- r-locfit=1.5_9.1=r3.3.2_2
- r-matrixstats=0.51.0=r3.3.2_1
- r-optparse=1.3.2=r3.3.2_0
- r-pheatmap=1.0.8=r3.3.2_0
- r-plotrix=3.6_4=r3.3.2_0
- r-rmarkdown=0.9.5=r3.3.2_0
- r-scales=0.4.1=r3.3.2_1
- r-sendmailr=1.2_1=r3.3.2_0
- r-snow=0.4_1=r3.3.2_0
- r-tibble=1.2=r3.3.2_1
- r-upsetr=1.0.3=r3.3.2_1
- r-viridis=0.3.1=r3.3.2_0
- r-yaml=2.1.13=r3.3.2_1
- samtools=1.5=0
- snakemake=3.13.3=py36_0
- sra-tools=2.8.2=0
- star=2.5.3a=0
- tbb=4.4_20150728=0
- trimmomatic=0.36=4
- asn1crypto=0.22.0=py36_0
- bzip2=1.0.6=1
- cairo=1.14.6=4
- certifi=2017.4.17=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.2=py36_1
- cryptography=1.9=py36_0
- curl=7.54.1=0
- cycler=0.10.0=py36_0
- dbus=1.10.10=3
- docutils=0.13.1=py36_0
- expat=2.2.1=0
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- gmp=6.1.2=0
- graphite2=1.3.9=0
- gsl=1.16=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- harfbuzz=1.4.3=0
- icu=58.1=1
- idna=2.5=py36_0
- jpeg=9b=0
- krb5=1.14.2=0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=1
- libssh2=1.8.0=1
- libtiff=4.0.6=7
- libxcb=1.12=1
- libxml2=2.9.4=4
- matplotlib=2.0.2=py36_1
- ncurses=5.9=10
- pandas=0.20.3=py36_1
- pango=1.40.4=0
- paramiko=2.2.1=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=0
- perl=5.22.0.1=0
- pixman=0.34.0=0
- psutil=5.2.1=py36_0
- pyasn1=0.2.3=py36_0
- pycparser=2.18=py36_0
- pynacl=1.1.2=py36_0
- pyopenssl=16.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.7=py36_0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_1
- qt=5.6.2=3
- r=3.3.2=r3.3.2_0
- r-acepack=1.4.1=r3.3.2_0
- r-assertthat=0.1=r3.3.2_0
- r-backports=1.0.5=r3.3.2_0
- r-base=3.3.2=5
- r-base64enc=0.1_3=r3.3.2_0
- r-bitops=1.0_6=r3.3.2_0
- r-boot=1.3_18=r3.3.2_0
- r-brew=1.0_6=r3.3.2_0
- r-class=7.3_14=r3.3.2_0
- r-cluster=2.0.6=r3.3.2_0
- r-codetools=0.2_15=r3.3.2_0
- r-colorspace=1.3_2=r3.3.2_0
- r-dbi=0.6_1=r3.3.2_0
- r-dichromat=2.0_0=r3.3.2_0
- r-doparallel=1.0.10=r3.3.2_0
- r-evaluate=0.10=r3.3.2_0
- r-foreach=1.4.3=r3.3.2_0
- r-foreign=0.8_67=r3.3.2_0
- r-formatr=1.4=r3.3.2_0
- r-formula=1.2_1=r3.3.2_0
- r-gdata=2.17.0=r3.3.2_0
- r-gridbase=0.4_7=r3.3.2_0
- r-gridextra=2.2.1=r3.3.2_0
- r-gtable=0.2.0=r3.3.2_0
- r-gtools=3.5.0=r3.3.2_0
- r-highr=0.6=r3.3.2_0
- r-hmisc=4.0_3=r3.3.2_0
- r-htmltable=1.9=r3.3.2_0
- r-igraph=1.0.1=r3.3.2_0
- r-irlba=2.1.2=r3.3.2_0
- r-iterators=1.0.8=r3.3.2_0
- r-kernsmooth=2.23_15=r3.3.2_0
- r-labeling=0.3=r3.3.2_0
- r-lattice=0.20_34=r3.3.2_0
- r-latticeextra=0.6_28=r3.3.2_0
- r-lazyeval=0.2.0=r3.3.2_0
- r-magrittr=1.5=r3.3.2_0
- r-markdown=0.8=r3.3.2_0
- r-mass=7.3_45=r3.3.2_0
- r-matrix=1.2_7.1=r3.3.2_0
- r-memoise=1.1.0=r3.3.2_0
- r-mgcv=1.8_17=r3.3.2_0
- r-mime=0.5=r3.3.2_0
- r-munsell=0.4.3=r3.3.2_0
- r-nlme=3.1_131=r3.3.2_0
- r-nmf=0.20.6=r3.3.2_0
- r-nnet=7.3_12=r3.3.2_0
- r-pkgmaker=0.22=r3.3.2_0
- r-plogr=0.1_1=r3.3.2_0
- r-plyr=1.8.4=r3.3.2_0
- r-r6=2.2.0=r3.3.2_0
- r-rcolorbrewer=1.1_2=r3.3.2_0
- r-rcpp=0.12.10=r3.3.2_0
- r-rcpparmadillo=0.7.800.2.0=r3.3.2_0
- r-rcurl=1.95_4.8=r3.3.2_0
- r-recommended=3.3.2=r3.3.2_0
- r-registry=0.3=r3.3.2_0
- r-reshape2=1.4.2=r3.3.2_0
- r-rjava=0.9_8=r3.3.2_0
- r-rjson=0.2.15=r3.3.2_0
- r-rngtools=1.2.4=r3.3.2_0
- r-rpart=4.1_10=r3.3.2_0
- r-rsqlite=1.1_2=r3.3.2_0
- r-sparsem=1.76=r3.3.2_0
- r-spatial=7.3_11=r3.3.2_0
- r-stringi=1.1.2=r3.3.2_0
- r-stringr=1.1.0=r3.3.2_0
- r-survival=2.40_1=r3.3.2_0
- r-xlsx=0.5.7=r3.3.2_0
- r-xlsxjars=0.6.1=r3.3.2_0
- r-xml=3.98_1.6=r3.3.2_0
- r-xtable=1.8_2=r3.3.2_0
- readline=6.2=0
- requests=2.18.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- statsmodels=0.8.0=np112py36_0
- tornado=4.5.1=py36_0
- urllib3=1.21.1=py36_1
- wrapt=1.10.8=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- yaml=0.1.6=0
- bcrypt=3.1.3=py36_0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- numpy=1.12.1=py36_0
- openjdk=8.0.121=1
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- scipy=0.19.1=np112py36_0
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - htseq==0.9.1
prefix: /home/xfu/miniconda2/envs/gmatic

